let sb=null,catalog=[],selectedBaggage={},selectedInsurance=null;
const $=(s,r=document)=>r.querySelector(s), rupiah=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||"null")}catch{return null}};
const flight=read("otw_selected_flight")||read("otw_flight_selected")||read("selectedFlight")||read("otw_flight_detail")||{};
const paxData=read("otw_passenger_details")||{};
const passengers=Array.isArray(paxData.passengers)&&paxData.passengers.length?paxData.passengers:[{firstName:"Penumpang",lastName:"1"}];
function code(){return String(flight.airlineCode||flight.airline_code||flight.airline?.code||flight.carrierCode||flight.validatingAirline||flight.segments?.[0]?.airlineCode||flight.segments?.[0]?.carrierCode||"").toUpperCase()}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
async function getSB(){try{const m=await import("./supabase.js");return [m.supabase,m.default,m.supabaseClient,window.supabaseClient,window.otwSupabase].find(x=>x&&typeof x.rpc==="function")||null}catch{return [window.supabaseClient,window.otwSupabase].find(x=>x&&typeof x.rpc==="function")||null}}
function flightHead(){const from=flight.origin||flight.from||flight.departure?.iata||flight.segments?.[0]?.origin||"—",to=flight.destination||flight.to||flight.arrival?.iata||flight.segments?.at(-1)?.destination||"—";$("#route").textContent=`${from} → ${to}`;$("#airline").textContent=[flight.airlineName||flight.airline?.name||code(),flight.flightNumber||flight.flight_number].filter(Boolean).join(" · ")||"Penerbangan terpilih"}
function bagOptions(){return catalog.filter(x=>x.addon_type==="BAGGAGE"&&(x.airline_code==="ALL"||x.airline_code===code()))}
function insuranceOptions(){return catalog.filter(x=>x.addon_type==="INSURANCE"&&(x.airline_code==="ALL"||x.airline_code===code()))}
function empty(msg,sub){return `<div class="empty"><b>${esc(msg)}</b><small>${esc(sub)}</small></div>`}
function render(){
 const bags=bagOptions(),ins=insuranceOptions();
 if(!bags.length) $("#baggage").innerHTML=empty("Bagasi tambahan belum tersedia",code()?`Belum ada harga aktif untuk maskapai ${code()}.`:"Kode maskapai penerbangan tidak terbaca.");
 else $("#baggage").innerHTML=`<div class="box">${passengers.map((p,i)=>`<div class="pax"><div class="pax-head"><b>${esc([p.firstName||p.first_name||p.name,p.lastName||p.last_name].filter(Boolean).join(" ")||`Penumpang ${i+1}`)}</b><small>${selectedBaggage[i]?.addon_name||"Belum dipilih"}</small></div><div class="options"><button type="button" class="option ${!selectedBaggage[i]?"active":""}" data-pax="${i}" data-none="1"><i class="check"></i><b>Tanpa bagasi</b><small>Tidak ada tambahan</small><strong>Rp0</strong></button>${bags.map(x=>`<button type="button" class="option ${selectedBaggage[i]?.id===x.id?"active":""}" data-pax="${i}" data-id="${x.id}"><i class="check"></i><b>${esc(x.addon_name)}</b><small>${x.weight_kg?`Tambahan ${x.weight_kg} kg`:"Bagasi tambahan"}</small><strong>${rupiah(x.selling_price)}</strong></button>`).join("")}</div></div>`).join("")}</div>`;
 if(!ins.length) $("#insurance").innerHTML=empty("Asuransi belum tersedia","Belum ada paket INSURANCE aktif di Admin Add-on Pricing.");
 else $("#insurance").innerHTML=`<div class="box"><div class="options"><button type="button" class="option ${!selectedInsurance?"active":""}" data-ins-none="1"><i class="check"></i><b>Tanpa asuransi</b><small>Tidak dipilih</small><strong>Rp0</strong></button>${ins.map(x=>`<button type="button" class="option ${selectedInsurance?.id===x.id?"active":""}" data-ins="${x.id}"><i class="check"></i><b>${esc(x.addon_name)}</b><small>Perlindungan perjalanan</small><strong>${rupiah(x.selling_price)}</strong></button>`).join("")}</div></div>`;
 document.querySelectorAll("[data-pax]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.pax);selectedBaggage[i]=b.dataset.none?null:bags.find(x=>x.id===b.dataset.id)||null;render()});
 document.querySelectorAll("[data-ins-none]").forEach(b=>b.onclick=()=>{selectedInsurance=null;render()});
 document.querySelectorAll("[data-ins]").forEach(b=>b.onclick=()=>{selectedInsurance=ins.find(x=>x.id===b.dataset.ins)||null;render()});
 summary();
}
function summary(){let rows=[],total=0;Object.entries(selectedBaggage).forEach(([i,x])=>{if(x){total+=Number(x.selling_price||0);rows.push(`<div class="sumrow"><span>Bagasi · ${esc(passengers[i]?.firstName||passengers[i]?.name||`Pax ${Number(i)+1}`)}<small>${esc(x.addon_name)}</small></span><b>${rupiah(x.selling_price)}</b></div>`)}});if(selectedInsurance){total+=Number(selectedInsurance.selling_price||0);rows.push(`<div class="sumrow"><span>Asuransi perjalanan<small>${esc(selectedInsurance.addon_name)}</small></span><b>${rupiah(selectedInsurance.selling_price)}</b></div>`)}$("#summaryRows").innerHTML=rows.join("")||'<div class="sumrow"><span>Belum ada tambahan<small>Anda dapat melanjutkan tanpa add-on.</small></span><b>Rp0</b></div>';$("#total").textContent=$("#footerTotal").textContent=rupiah(total)}
function payload(){const baggage=Object.entries(selectedBaggage).filter(([,x])=>x).map(([i,x])=>({passengerIndex:Number(i),addonId:x.id,code:x.addon_code,name:x.addon_name,weightKg:x.weight_kg,price:Number(x.selling_price||0)}));const insurance=selectedInsurance?{addonId:selectedInsurance.id,code:selectedInsurance.addon_code,name:selectedInsurance.addon_name,price:Number(selectedInsurance.selling_price||0)}:null;return {airlineCode:code(),baggage,insurance,total:baggage.reduce((a,x)=>a+x.price,0)+(insurance?.price||0),savedAt:new Date().toISOString()}}
function saveNext(){localStorage.setItem("otw_flight_addons",JSON.stringify(payload()));location.href="./flight-review.html"}
async function load(){flightHead();sb=await getSB();if(!sb){$("#baggage").innerHTML=empty("Koneksi database belum tersedia","Pastikan supabase.js berada sejajar dengan halaman ini.");$("#insurance").innerHTML=empty("Koneksi database belum tersedia","Katalog add-on tidak dapat dimuat.");return}const c=code();if(!c){render();return}const {data,error}=await sb.rpc("get_public_addon_catalog",{p_airline_code:c});if(error){console.error(error);$("#baggage").innerHTML=empty("Katalog gagal dimuat",error.message);$("#insurance").innerHTML=empty("Katalog gagal dimuat","Periksa RPC get_public_addon_catalog.");return}catalog=data||[];const old=read("otw_flight_addons");if(old?.airlineCode===c){(old.baggage||[]).forEach(x=>{const f=catalog.find(y=>String(y.id)===String(x.addonId));if(f)selectedBaggage[x.passengerIndex]=f});if(old.insurance){selectedInsurance=catalog.find(y=>String(y.id)===String(old.insurance.addonId))||null}}render()}
$("#resetBtn").onclick=()=>{selectedBaggage={};selectedInsurance=null;render();toast("Pilihan direset.")};$("#skipBtn").onclick=()=>{selectedBaggage={};selectedInsurance=null;saveNext()};$("#continueBtn").onclick=saveNext;$("#backBtn").onclick=()=>history.length>1?history.back():location.href="./passenger-details.html";load();