import { supabase } from "./supabase.js";
const $=s=>document.querySelector(s);let user=null,order=null,countdownTimer=null;
const rupiah=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
const hm=v=>{const m=String(v||"").match(/T(\d{2}):(\d{2})/);return m?`${m[1]}:${m[2]}`:"--:--"};
const dateLabel=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric"}).format(d)};
const dateTime=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}
const orderCode=()=>new URLSearchParams(location.search).get("id")||"";
async function ensureAuth(){const {data,error}=await supabase.auth.getSession();if(error)throw error;user=data?.session?.user||null;if(!user){location.replace("login.html");return false}return true}
async function loadOrder(){const code=orderCode();if(!code)throw new Error("Nomor pesanan tidak ditemukan.");const {data,error}=await supabase.from("flight_orders").select("*").eq("order_code",code).single();if(error)throw error;if(data.user_id&&data.user_id!==user.id)throw new Error("Pesanan ini bukan milik akun Anda.");order=data;const status=String(order.status||"").toUpperCase();if(!["COMPLETED","PAID"].includes(status))throw new Error("Pembayaran belum tersedia untuk pesanan ini.")}
function resolveFlight(){const p=order.payload||{},f=p.flight||{},segs=Array.isArray(f.segments)?f.segments:[],first=segs[0]||{},search=f.searchSnapshot||p.search||{};const origin=String(search.origin||first.origin||f.origin||order.origin||"---").toUpperCase();const destination=String(search.destination||f.destination||order.destination||"---").toUpperCase();const last=segs.find(s=>String(s.destination||"").toUpperCase()===destination)||segs[segs.length-1]||first;return{first,last,origin,destination,depart:first.departureLocalTime||first.departureTime||order.depart_at,arrive:last.arrivalLocalTime||last.arrivalTime||order.arrival_at,airline:first.carrierName||f.airlineName||order.airline_name||"Maskapai",flightNo:first.flightNumber||f.flightNumber||order.flight_number||"—",trip:String(search.trip||"").toLowerCase()==="roundtrip"?"Pulang-pergi":"Sekali jalan"}}
function completedAt(){const p=order.payload||{};return order.completed_at||p?.ticketing?.completedAt||p?.completedAt||order.updated_at||new Date().toISOString()}
function deadline(){const start=new Date(completedAt());return new Date(start.getTime()+14*86400000)}
function paymentSnapshot(){const p=order.payload||{},pricing=p.pricing||{};const flight=Number(order.flight_total??pricing.flightTotal??0),baggage=Number(pricing.baggageTotal||0),insurance=Number(pricing.insuranceTotal||0),serviceFee=Number(pricing.serviceFee||pricing.service_fee||0),grand=Number(order.grand_total??pricing.grandTotal??flight+baggage+insurance+serviceFee);return{flight,baggage,insurance,serviceFee,grand}}
function paymentState(){const p=order.payload?.payment||{},state=String(p.transaction_status||p.status||order.payment_status||"").toLowerCase();if(["settlement","capture","paid","success"].includes(state)||String(order.status).toUpperCase()==="PAID")return"paid";return"waiting"}
function render(){const f=resolveFlight(),price=paymentSnapshot();$("#orderCodeTop").textContent=order.order_code;$("#billOrder").textContent=order.order_code;["#grandTotal","#billGrandTotal","#footerTotal"].forEach(s=>$(s).textContent=rupiah(price.grand));$("#flightTotal").textContent=rupiah(price.flight);$("#baggageTotal").textContent=rupiah(price.baggage);$("#insuranceTotal").textContent=rupiah(price.insurance);$("#baggageRow").classList.toggle("hidden",!price.baggage);$("#insuranceRow").classList.toggle("hidden",!price.insurance);if(price.serviceFee){$("#serviceFeeRow").classList.remove("hidden");$("#serviceFee").textContent=rupiah(price.serviceFee)}$("#airline").textContent=f.airline;$("#flightNumber").textContent=f.flightNo;$("#tripType").textContent=f.trip;$("#origin").textContent=f.origin;$("#destination").textContent=f.destination;$("#departAt").textContent=`${dateLabel(f.depart)} · ${hm(f.depart)}`;$("#arrivalAt").textContent=`${dateLabel(f.arrive)} · ${hm(f.arrive)}`;applyPaymentState(paymentState());startCountdown();$("#loadingState").classList.add("hidden");$("#content").classList.remove("hidden");$("#actionBar").classList.remove("hidden")}
function applyPaymentState(state){const badge=$("#paymentStatusBadge"),btn=$("#payBtn");if(state==="paid"){badge.className="status-pill paid";badge.innerHTML="<i></i> PEMBAYARAN BERHASIL";$("#paidSection").classList.remove("hidden");$("#heroSub").textContent="Pembayaran telah dikonfirmasi oleh sistem.";$("#footerLabel").textContent="Status pembayaran";$("#footerTotal").textContent="Lunas";btn.textContent="Lihat Invoice";btn.dataset.mode="invoice";return}badge.className="status-pill waiting";badge.innerHTML="<i></i> MENUNGGU PEMBAYARAN";btn.dataset.mode="pay"}
function startCountdown(){if(countdownTimer)clearInterval(countdownTimer);const due=deadline();$("#deadlineText").textContent=`s.d. ${dateTime(due)}`;const tick=()=>{const diff=due.getTime()-Date.now(),safe=Math.max(0,diff),days=Math.floor(safe/86400000),hours=Math.floor((safe%86400000)/3600000),overdue=diff<=0;$("#countdown").textContent=overdue?"Tempo berakhir":`${days}d ${String(hours).padStart(2,"0")}h`;document.body.classList.toggle("overdue",overdue);if(overdue&&paymentState()!=="paid"){$("#payBtn").disabled=true;$("#heroSub").textContent="Batas pembayaran telah berakhir. Hubungi Pusat Bantuan OTW."}};tick();countdownTimer=setInterval(tick,60000)}
function loadSnapScript(clientKey,environment){return new Promise((resolve,reject)=>{if(window.snap)return resolve();const s=document.createElement("script");s.src=environment==="production"?"https://app.midtrans.com/snap/snap.js":"https://app.sandbox.midtrans.com/snap/snap.js";s.dataset.clientKey=clientKey;s.onload=resolve;s.onerror=()=>reject(new Error("Gagal memuat Midtrans Snap."));document.head.appendChild(s)})}
async function createTransaction(){const btn=$("#payBtn"),old=btn.textContent;btn.disabled=true;btn.textContent="Menyiapkan Midtrans...";try{const {data,error}=await supabase.functions.invoke("midtrans-create-payment",{body:{orderCode:order.order_code}});if(error)throw error;if(!data?.ok)throw new Error(data?.message||"Gagal membuat transaksi.");await loadSnapScript(data.clientKey,data.environment||"sandbox");window.snap.pay(data.snapToken,{onSuccess:async()=>{toast("Pembayaran berhasil. Memverifikasi...");await refreshPayment()},onPending:async()=>{toast("Pembayaran dibuat. Menunggu konfirmasi.");await refreshPayment()},onError:()=>toast("Pembayaran gagal. Silakan coba metode lain."),onClose:()=>toast("Jendela pembayaran ditutup.")})}catch(e){console.error(e);toast(e.message||"Pembayaran belum dapat diproses.")}finally{btn.disabled=false;btn.textContent=old}}
async function refreshPayment(){const {data,error}=await supabase.from("flight_orders").select("*").eq("order_code",order.order_code).single();if(!error&&data){order=data;applyPaymentState(paymentState());if(paymentState()==="paid")toast("Pembayaran telah dikonfirmasi.")}}
$("#backBtn").onclick=()=>history.length>1?history.back():location.href=`detail-pesanan.html?id=${encodeURIComponent(orderCode())}`;$("#retryBtn").onclick=()=>location.reload();$("#helpBtn").onclick=()=>location.href="help.html";$("#payBtn").onclick=()=>{$("#payBtn").dataset.mode==="invoice"?location.href=`invoice.html?id=${encodeURIComponent(order.order_code)}`:createTransaction()};
(async()=>{try{if(!await ensureAuth())return;await loadOrder();render()}catch(e){console.error(e);$("#loadingState").classList.add("hidden");$("#errorState").classList.remove("hidden");$("#errorText").textContent=e.message||"Pembayaran belum dapat dimuat."}})();
